.github: Fix integrated timescape CI failure
The jsonpath expression was changed in
https://github.com/isovalent/cilium/pull/7358 which broke the query. An
invalid jsonpath filter doesn't cause the command to fail so it proceeds
regardless.

Signed-off-by: Chance Zibolski <chance.zibolski@gmail.com>

diff --git a/.github/workflows/enterprise-kind-integrated-timescape.yaml b/.github/workflows/enterprise-kind-integrated-timescape.yaml
--- a/.github/workflows/enterprise-kind-integrated-timescape.yaml
+++ b/.github/workflows/enterprise-kind-integrated-timescape.yaml
@@ -144,8 +144,12 @@ jobs:
 
       - name: Get client certificate
         run: |
-          kubectl -n kube-system get secret hubble-timescape-client-certs  -o jsonpath='{.data."tls\.crt"}' | base64 -d > client.crt
-          kubectl -n kube-system get secret hubble-timescape-client-certs  -o jsonpath='{.data."tls\.key"}' | base64 -d > client.key
+          kubectl -n kube-system get secret hubble-timescape-client-certs  -o jsonpath='{.data.tls\.crt}' | base64 -d > client.crt
+          kubectl -n kube-system get secret hubble-timescape-client-certs  -o jsonpath='{.data.tls\.key}' | base64 -d > client.key
+          if [ ! -s client.crt ] || [ ! -s client.key ]; then
+            echo "Failed to retrieve client certificate and key, they are empty."
+            exit 1
+          fi
         shell: bash
 
       - name: Run tests
